# site settings

title: Alexander Mchedlishvili
description: This page is meant to serve as a curriculum vitae
taglong: Polar Satellite Remote Sensing Ph.D. Candidate, Programmer, Science Communicator
tagshort: Ph.D. Candidate, Scientist, Programmer, Science Communicator
url: https://alex-mchedlishvili.github.io/
baseurl: ""
permalink: pretty
repo: github.com/Alex-Mchedlishvili/Alex-Mchedlishvili.github.io

# author settings

author:
  name: Alexander Mchedlishvili
  email: alexander.mchedlishvili.jobs@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: username
  github: username
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
